services:
    _defaults:
        autowire: true
        autoconfigure: true

    ApexToolbox\SymfonyLogger\EventListener\LoggerListener:
        arguments:
            $parameterBag: '@parameter_bag'
            $kernel: '@kernel'
        tags:
            - { name: kernel.event_subscriber }

    ApexToolbox\SymfonyLogger\LogProcessor:
        tags:
            - { name: monolog.processor, method: __invoke }